/* per-machine configuration. this file is automatically generated. */

#ifndef _ODE_CONFIG_H_
#define _ODE_CONFIG_H_

/* standard system headers */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include <malloc.h>
#include <alloca.h>
#include <values.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif


/* an integer type that we can safely cast a pointer to and
 * from without loss of bits.
 */
typedef unsigned int intP;

/* select the base floating point type */
#define dDOUBLE 1

/* the floating point infinity */
#define dInfinity DBL_MAX

/* available functions */

#ifdef __cplusplus
}
#endif
#endif
